# Generated by Django 4.2.9 on 2024-03-12 09:42

from django.db import migrations, models
import django.db.models.deletion
import lib.fields
from deviations.models import DeadlineRuleDeviation, MaxSubmissionsRuleDeviation
from deviations.viewbase import get_deviation_groups

def merge_deviation_group(deviation_group):
    can_group = deviation_group[1]
    if can_group:
        devs = deviation_group[0]
        d = devs[0]
        d.module = d.exercise.course_module
        d.exercise = None
        d.save()
        for deviation in devs[1:]:
            deviation.delete()

def make_module_deviations(apps, schema_editor):
    dl_deviations = DeadlineRuleDeviation.objects.all()
    dl_deviation_groups = get_deviation_groups(dl_deviations)
    for g in dl_deviation_groups:
        merge_deviation_group(g)

    submission_deviations = MaxSubmissionsRuleDeviation.objects.all()
    submission_deviation_groups = get_deviation_groups(submission_deviations)
    for g in submission_deviation_groups:
        merge_deviation_group(g)

class Migration(migrations.Migration):

    dependencies = [
        ('course', '0058_coursemodule_model_answer_and_more'),
        ('exercise', '0049_submission_unofficial_submission_type'),
        ('deviations', '0006_rename_extra_minutes_deadlineruledeviation_extra_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlineruledeviation',
            name='module',
            field=lib.fields.DefaultForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodule', verbose_name='LABEL_MODULE'),
        ),
        migrations.AddField(
            model_name='maxsubmissionsruledeviation',
            name='module',
            field=lib.fields.DefaultForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodule', verbose_name='LABEL_MODULE'),
        ),
        migrations.AlterField(
            model_name='deadlineruledeviation',
            name='exercise',
            field=lib.fields.DefaultForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='maxsubmissionsruledeviation',
            name='exercise',
            field=lib.fields.DefaultForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AddConstraint(
            model_name='deadlineruledeviation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('exercise__isnull', True), ('module__isnull', False)), models.Q(('exercise__isnull', False), ('module__isnull', True)), _connector='OR'), name='deadlineruledeviation_require_exercise_or_module'),
        ),
        migrations.AddConstraint(
            model_name='maxsubmissionsruledeviation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('exercise__isnull', True), ('module__isnull', False)), models.Q(('exercise__isnull', False), ('module__isnull', True)), _connector='OR'), name='maxsubmissionsruledeviation_require_exercise_or_module'),
        ),
        migrations.RunPython(make_module_deviations),
    ]